### PR TITLE
add mithril 1.1.1 support

### PR DESCRIPTION
**Pull request by dfadev**
Nice project! 

Didn't work with mithril 1.1.1 for me without these patches.  add "-D mithril_111" to use.

### CODE REVIEW

**Comment by benmerckx** [comment]
Nice! I need some time to check this. I'm also pretty convinced the [components](https://github.com/benmerckx/ithril#components) won't work at all, but I feel they need to be completely revised anyway.

**Comment by dfadev** [comment]
You are correct, components are broken.  Dangit :)

Have you considered removing ComponentCache?  Is it only necessary if you store state within the component?

**Comment by benmerckx** [comment]
Well, a lot can be removed since https://github.com/MithrilJS/mithril.js/pull/1339 is merged. They should reflect a mithril component as closely as possible (eg the same lifecycle methods and attrs/state). However the projects I use ithril in I doubt will see a refactor to mithril 1, so I don't think I'll get round to this soon. Are you actually using this? It might make sense to release a new version without components for now.

**Comment by dfadev** [comment]
I'm going to use it for a hobby project - but I need components working..  so eventually it'll get there.

Working on getting the tests and HTMLRenderer working, but the concept of letting mithril instance components appears sound.

**Comment by benmerckx** [comment]
I gave you push acces to the repository. As I see it this should live on as ithril v2, while I can take care of any updates to the older (v1, mithril 0.2.x) version. I'm not entirely sure if adding you to the haxelib.json authors would also grant you rights to make haxelib releases but let's give a try once you're done.

**Comment by dfadev** [comment]
OK!  Going to let this simmer for a few days to see what bugs pop out and then I'll merge + `submit.sh`.

**Pull request merged**
